### ISSUE TITLE
组件中使用，传入componentThis: this 无效

### ISSUE THREAD

**Issue by qianweichen** [TuiMao233/u-draw-poster#1]
const dp = await DrawPoster.build({
				selector: 'canvas',
				componentThis: this
			});
提示draw-poster 构建完成，但是一直在等待

**Comment by Leefrom** [comment]
微信小程序亲测是ok的 你是什么端？

**Comment by qianweichen** [comment]
> 微信小程序亲测是ok的 你是什么端？

是小程序端，我是在组件中使用的。
组件中使用传递this对象，工具中没有接收。新版本已经修复了。。。

**Comment by qianweichen** [comment]
> 微信小程序亲测是ok的 你是什么端？

**Comment by qianweichen** [comment]
> 微信小程序亲测是ok的 你是什么端？

是微信小程序，在组件中使用的。
工具的老版本中没有接收this，新版本貌似修复过了

**Comment by TuiMao233** [comment]
已在新版本中修复

**Comment by TuiMao233** [comment]
测试未发现问题，请提供现在所使用的版本，已经是版本问题。
![image](https://user-images.githubusercontent.com/49724027/101568119-0652af00-3a0d-11eb-94d0-b48e5d5a75dc.png)
![image](https://user-images.githubusercontent.com/49724027/101568133-0baff980-3a0d-11eb-94c8-c201cd41a2d7.png)
![image](https://user-images.githubusercontent.com/49724027/101568143-110d4400-3a0d-11eb-96ee-163d076dbbd0.png)
