### ISSUE TITLE
iphoneX和iphoneXS绘制图片不显示

### ISSUE THREAD

**Issue by Juaoie** [TuiMao233/u-draw-poster#11]
在最新版本的ios系统上使用drawImage方法绘制图片不显示出来；iphone7是ok的

**Comment by TuiMao233** [comment]
请提供运行环境，和执行代码

**Comment by TuiMao233** [comment]
已更新，请帮忙测试是否修复成功。

**Comment by Juaoie** [comment]
好的，蟹蟹了😊

**Comment by Juaoie** [comment]
测试了1.1.33版本的代码，还是存在该问题；
[测试代码链接](http://uaoie.top/images/bug/bug.zip)
测试环境iphonex；测试系统ios14

**Comment by TuiMao233** [comment]
已找到问题：[微信iOS 7.0.20 版本 canvas 2d 绘图无法drawImage图片](https://developers.weixin.qq.com/community/develop/doc/0008c6334f40c8c3847b5ff4b5ec00?highLine=canvas%25202d)

解决方法：关闭 type2d 方式或等待微信官方修复问题。

![image](https://user-images.githubusercontent.com/49724027/104262097-dee67a80-54c1-11eb-977d-8299f3d9b076.png)
