### ISSUE TITLE
hideLoading 关闭时机问题

### ISSUE THREAD

**Issue by wasdokij** [TuiMao233/u-draw-poster#13]
draw-poster.js 文件里  awaitCreate 函数，createImagePath函数
注意：里面有 2个  resolve(tips); 

// 当前绘制为 context 绘制
  return await new Promise((resolve) => {
      this.ctx.draw(true, () => {     // 这个执行时间 可能 会晚于 下面setTimeout，因为每个手机的绘制能力不一
          resolve(tips);
          this.loading && gbl.hideLoading();
      });
      // 当环境是app时，ctx.draw 回调不触发, 手动定时器触发
     //  没有 执行完 this.ctx.draw 就   resolve(tips); 会导致 this.loading && gbl.showLoading(‘生成图片中...’); 被过早关闭
      if (PLATFORM === "app-plus") {
          const time = this.ctx.existDrawImage ? this.drawImageTime : 0;
          this.ctx.existDrawImage = false;
          setTimeout(() => {
              resolve(tips); 
              this.loading && gbl.hideLoading();
          }, time);
      }
  });

**Comment by TuiMao233** [comment]
我在测试环境是app时，ctx.draw没有执行，可在配置项中手动设置图片绘制时间
![image](https://user-images.githubusercontent.com/49724027/104262340-5e744980-54c2-11eb-8bdc-867857e056ff.png)

**Comment by wasdokij** [comment]
> 目前，我在测试环境是app时，ctx.draw没有执行，你那边执行了吗？
> ![图片](https://user-images.githubusercontent.com/49724027/104262340-5e744980-54c2-11eb-8bdc-867857e056ff.png)

是的 我好几个华为手机执行了，而且线上项目上使用未发现有ctx.draw不返回异常

**Comment by TuiMao233** [comment]
好的，暂时先使用 drawImageTime 自定义图片绘制时间，这个问题在以后会修复。

**Comment by TuiMao233** [comment]
问题已修复。
