### ISSUE TITLE
HBuilderX 3.1.0 alpha以上会出现 canvas截取不完整

### ISSUE THREAD

**Issue by wasdokij** [TuiMao233/u-draw-poster#14]
**问题描述，及官方回答：**
[问题反馈地址https://ask.dcloud.net.cn/question/111225](https://ask.dcloud.net.cn/question/111225)
获取canvas的大小，不要用其他元素的大小来替代。另外x、y、width、height、destWidth、destHeight均可缺省。

可以可以下载 HBuilderX 3.1.0 alpha，运行 绘制海拔就可以重现问题

**解决方案：**
draw-poster.js

```js
const options = Object.assign({ x: 0, y: 0, width: canvas.width, height: canvas.height, destWidth: canvas.width * 2, destHeight: canvas.height * 2 }, baseOptions);

 // 改成
const options = Object.assign({}, baseOptions);
```

**Comment by TuiMao233** [comment]
收到，新版本将会修复
