### ISSUE TITLE
苹果端真机调试场景下报错

### ISSUE THREAD

**Issue by aliang888** [TuiMao233/u-draw-poster#16]
v1.1.36，直接用你的demo，在开发工具中点“**真机调试**”然后，扫码测试，
但体验版或发布版又不会报下面错

Unhandled promise rejection TypeError: n.Canvas is not a constructor at t.value (eval at n.call.document (runtime.js?devtools_ignore=true:1), :2:2224602) at t.value (eval at n.call.document (runtime.js?devtools_ignore=true:1), :2:1866342) at A (eval at n.call.document (runtime.js?devtools_ignore=true:1), :2:1866508) at t.value (eval at n.call.document (runtime.js?devtools_ignore=true:1), :2:1866619) at eval (eval at n.call.document (runtime.js?devtoolsignore=true:1), :2:2559099) at new (eval at n.call.document (runtime.js?devtools_ignore=true:1), :2:67394) at ac (eval at n.call.document (runtime.js?devtools_ignore=true:1), :2:2559061) at eval (eval at n.call.document (runtime.js?devtools_ignore=true:1), :2:2560523) at Array.forEach () at n (eval at n.call.document (runtime.js?devtools_ignore=true:1), :2:2560501)

**Comment by aliang888** [comment]
微信小程序，真机调试，哎呀这里传不了图片
安卓红米note7 pro
微信版本：8.0.1
基础库版版：2.15.0[510]

**Comment by TuiMao233** [comment]
好的，我会进行检查。

**Comment by TuiMao233** [comment]
详情请看 canvas 2d ios 真机调试报错：https://developers.weixin.qq.com/community/develop/doc/0002aaa1564fa89c446a1d94c51400
