### ISSUE TITLE
微信小程序ios createImagePath方法没有返回

### ISSUE THREAD

**Issue by Juaoie** [TuiMao233/u-draw-poster#23]
iphone7、ios12、u-draw-poste1.1.5版本
执行createImagePath方法没有返回
源码中的resolve执行了
![image](https://user-images.githubusercontent.com/34809384/134643666-fb067b26-f27b-4e75-94a8-202c7d932f7e.png)
解决方案：将源码编译为es5就可以了
但是理论应该是对es6语法支持的才对

**Comment by TuiMao233** [comment]
这个有点奇怪，有报什么错误吗？

**Comment by carefree2021** [comment]
你好 苹果手机 图片绘制不成功 一片空白 用了示例demo也是一片空白

**Comment by Juaoie** [comment]
u-draw-poster版本多少呢？可以开debug开下输出日志，再不行调试一下源码，看问题是不是和我这个一样 @carefree2021
