### ISSUE TITLE
大佬，更新一下插件的依赖啊

### ISSUE THREAD

**Issue by levi-Ma** [TuiMao233/u-draw-poster#28]
![image](https://user-images.githubusercontent.com/37390166/158120809-31af0d10-c550-4ca7-9e75-137b25478bfd.png)

**Comment by TuiMao233** [comment]
[feat: 2.5.1 pub vue@3 test finish](https://github.com/TuiMao233/u-draw-poster/commit/67b889be61b6622f74e34f3dacc0e1817a74ee7f)
