### ISSUE TITLE
2.2.1 版本 vite+vue3 问题汇总

### ISSUE THREAD

**Issue by lidongtony** [TuiMao233/u-draw-poster#29]
问题1：微信小程序平台 使用vite+vue3 上无法正常使用 提示
![image](https://user-images.githubusercontent.com/16027524/158365406-bbdfc9de-0957-48b8-a656-abb57fdb7f48.png)

问题2：H5端dp.createImagePath()方法返回值不是最终绘制的图像，缺少最后绘制的图片元素（已经使用await语法 并没什么用）

问题3: H5端 ctx.drawRoundImage 可以绘制图片但是不能画圆 ，drawImageFit绘制无效果

**Comment by CLiangs** [comment]
h5无法绘制多张图片，只会显示最后一张图片

**Comment by TuiMao233** [comment]
收到，有空解决

**Comment by TuiMao233** [comment]
[feat: 2.5.1 pub vue@3 test finish](https://github.com/TuiMao233/u-draw-poster/commit/67b889be61b6622f74e34f3dacc0e1817a74ee7f)
