### ISSUE TITLE
华为P40  华为mate20 PRO  不能绘制图片，无报错。

### ISSUE THREAD

**Issue by yaozeyan** [TuiMao233/u-draw-poster#32]
走到创建绘制工具步不往下运行了。
const dp = await DrawPoster.build({
					selector: 'canvas',
					loading: true,
					debugging: true,
				});
插件版本1.1.5。uni-app使用的HBuilderX可视化工具创建的  版本不知道怎么看

**Comment by TuiMao233** [comment]
描述使用环境是什么？
App？微信小程序？
小程序的话版本是多少？

**Comment by yaozeyan** [comment]
微信小程序  小程序版本2.17.0

**Comment by TuiMao233** [comment]
DrawPoster.build 是什么时候的版本了，麻烦使用最新版本在试试问题，旧版本无法兼容
