### ISSUE TITLE
开发者工具显示正常，发布微信小程序白屏

### ISSUE THREAD

**Issue by huranccc** [TuiMao233/u-draw-poster#5]
开发者工具显示正常，发布微信小程序白屏，在体验版调试
代码运行到  
 const const dp = await DrawPoster.build(canvas);
后报错 cannot read property ‘done’ of undefined

**Comment by TuiMao233** [comment]
请提供运行环境，以及能实现的完整实例以便我这边复现。

**Comment by TuiMao233** [comment]
也许是因为 #8 问题导致的白屏现象，目前新版本已得到修复。
