### ISSUE TITLE
文档没了

### ISSUE THREAD

**Issue by djkloop** [TuiMao233/u-draw-poster#6]
文档没了

**Comment by TuiMao233** [comment]
请问是在哪里没了。

**Comment by djkloop** [comment]
> 请问是在哪里没了。

![image](https://user-images.githubusercontent.com/21050914/103356146-1a10a300-4aeb-11eb-94b7-f488a18b80ba.png)

**Comment by TuiMao233** [comment]
近期修复

**Comment by TuiMao233** [comment]
已修复
