### ISSUE TITLE
绘制表单，添加去除外边框功能。

### ISSUE THREAD

**Issue by Cjw-259** [TuiMao233/u-draw-poster#7]
请问绘制表单有没有办法，去除外边框，项目里只说明了去除内边框的方法，想把外边框也去掉

**Comment by Cjw-259** [comment]
有没有办法，将表单定位到画布的别的位置

**Comment by TuiMao233** [comment]
已添加文档，具体查看：http://tuimao233.gitee.io/mao-blog/my-extends/u-draw-poster/06-draw-from-list.html#%E7%BB%98%E5%88%B6%E5%B1%82

**Comment by TuiMao233** [comment]
> 有没有办法，将表单定位到画布的别的位置

由于表单绘制是一个复杂的应用，很可能没有办法做到这么灵活。
